### ISSUE TITLE
landmarker.io website only shows demo

### ISSUE THREAD

**Issue by mmcauliffe** [menpo/landmarkerio-server#17]
I ran lmio in the console, which opened https://www.landmarker.io/#mode=mesh&server=demo&t=ibug68&c=demo&i=1 in a web brower. The website only showed the demo face, rather than any of the assets in the directory I specified in the command line.  I don't quite know what the expected behaviour is, but from the installation instructions, it seems like it should display the meshes that I have locally despite the landmarker.io web address, correct?

**Comment by jabooth** [comment]
Can you try visiting 
http://insecure.landmarker.io/#server=localhost:5000
and see if that works?

To explain, we have moved www.landmarker.io to HTTPS in preparation for Dropbox (and to just be more secure). The way the landmarker works is that it make CORS (cross-origin) requests to a server, e.g. from www.landmarker.io (the client) to localhost:5000 (the server). You could have a server on any publicly accessible address, e.g. you could run a server at http://www.myfancylmioserver.com

The issue is that you are not allowed to do CORS requests from a secure domain (https) to a non-secure (http) one. As your localhost is not secure, added https support breaks the old workflow, which used to be that on startup the client would attempt to talk to localhost:5000 automatically.

To be clear, **from now on it will not be possible to connect to any http:// landmarkerio-server from www.landmarker.io**.

There are a few things we have done to alleviate this:

1. landmarkerio-sever will in the future really only be required by users running large annotation experiments with multiple annotators that want granular control over the experiment - we will discourage the use of landmarkerio-server on localhost. This need will be far better met by either our Dropbox integration, or use of the landmarker-app, which can natively access the local file system itself:
https://github.com/menpo/landmarker-app. Users using landmarkerio-server should be running the server over HTTPS, something that is easy and free to achieve with [ngrok](https://ngrok.com).
2. For users that want to continue with the existing workflow of using landmarkerio-server on localhost, there will be a mirror of landmarker.io hosted without HTTPS at http://insecure.landmarker.io. If you visit this link instead you will be able to talk to http servers without a problem.

Note that once our other solutions (Dropbox, local file system) have matured, we will deprecate the 
insecure subdomain, but this won't be for many months.

I will try to issue an update to landmarkerio-server that changes the localhost link to the one. For now you should be able to just visit it manually though to get on with the annotation.

**Comment by mmcauliffe** [comment]
It just redirects me to http://insecure.landmarker.io/#server=demo&t=ibug68&c=demo&i=1 instead, which is what the https version does too.

**Comment by jabooth** [comment]
@mmcauliffe thanks and apologies, looking into it now.

**Comment by jabooth** [comment]
OK, I've identified the problem, fix coming in a few hours.

**Comment by jabooth** [comment]
@mmcauliffe v0.3.1 has been released and should address all these issues. To upgrade:
```
conda install -c menpo landmarkerio
```
OS X and Linux builds are baked, and Windows is [on it's way](https://ci.appveyor.com/project/jabooth/landmarkerio-server/build/1.0.34)

**Comment by mmcauliffe** [comment]
Looks like it's working!  Thanks so much!

**Comment by jabooth** [comment]
@mmcauliffe great to hear!
